---
# file: roles/arista/tasks/main.yml

- name: set switchport default mode to routed
  arista.eos.eos_command:
    commands: show version #switchport default mode routed
  when: ansible_network_os == 'arista.eos.eos'

- name: set switchport default mode to routed
  arista.eos.eos_interfaces:
    config: show version #switchport default mode routed
  when: ansible_network_os == 'arista.eos.eos'
