---
# file: roles/arista/tasks/main.yml


- name: set switchport default mode to routed
  arista.eos.eos_config:
    lines: 'switchport default mode routed'
  when: ansible_network_os == 'arista.eos.eos'
