name: AVH_Deploy_Prod

# Controls when the workflow will run
on:
  push:
    branches: [ master ]

jobs:
  avh_deploy:
    name: "Deploy Azure Virtualization Host"
    uses: Nchaos/NaaS/.github/workflows/avh_deploy.yml@master
    with:
      environmentName: production
      resourceGroupName: usaf-naas-prod
      location: southcentralus
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMIN_PUBLIC_KEY: ${{ secrets.ADMIN_PUBLIC_KEY }}
