name: AVH_Deploy_Dev

on:
  push:
    branches: [ develop ]

jobs:
  avh_deploy:
    name: 'Deploy Azure Virtualization Host'
    uses: Nchaos/NaaS/.github/workflows/avh_deploy.yml@develop
    with:
      environmentName: development
      resourceGroupName: usaf-naas-dev
      location: southcentralus
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMIN_PUBLIC_KEY: ${{ secrets.ADMIN_PUBLIC_KEY }}
