# This is a basic workflow to help you get started with Actions

name: AVH_Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ResourceGroupName: nc-usaf-naas
      ResourceGroupLocation: "southcentralus"
    steps:
      - uses: actions/checkout@v2

      # Authenticate to Azure.
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Ensure ResourceGroup is created.
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --resource-group ${{ env.ResourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.ResourceGroupName }}
          template: azure/avh.json
          parameters: azure/avh.parameters.json adminPublicKey=${{ secrets.ADMIN_PUBLIC_KEY }}

