name: AVH_Deploy_Azure

on:
  push:
    branches: [ master ]
    paths:
    - 'azure/**'
    - '.github/workflows/avh_deploy.azure.yml'
    - '.github/workflows/avh_deploy.yml'

jobs:
  avh_deploy:
    name: 'Deploy Azure Virtualization Host'
    uses: Nchaos/NaaS/.github/workflows/avh_deploy.yml@master
    with:
      environment: Azure
      environmentShortName: prod
      resourceGroupName: usaf-naas-prod
      alias: nichao
      location: southcentralus
    secrets:
      AZURE_CREDS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMIN_PUB_KEY: ${{ secrets.ADMIN_PUB_KEY }}