name: AVH_Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      environmentCloud:
        required: false
        type: string
        default: azurecloud
      environmentShortName:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      alias:
        required: true
        type: string
    secrets:
      AZURE_CREDS:
        required: true
      ADMIN_PUB_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      location: "southcentralus"
    steps:
      - uses: actions/checkout@v2

      # Authenticate to Azure.
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDS }}
          environment: ${{ inputs.environmentCloud }}
          
      - name: Ensure ResourceGroup is created.
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --resource-group ${{ inputs.resourceGroupName }} --location ${{ env.location }} --tags "alias=${{ inputs.alias }}"
            echo "Azure resource group created"
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: azure/avh.json
          parameters: azure/avh.parameters.json environment=${{ inputs.environmentShortName }} adminPublicKey=${{ secrets.ADMIN_PUB_KEY }} location=${{ env.location }}