name: AVH_Deploy_MAG

on:
  push:
    branches: [ master ]
    paths:
    - 'azure/**'
    - '.github/workflows/avh_deploy.mag.yml'
    - '.github/workflows/avh_deploy.yml'

jobs:
  avh_deploy:
    name: 'Deploy Azure Virtualization Host'
    uses: Nchaos/NaaS/.github/workflows/avh_deploy.yml@master
    with:
      environment: 'Azure US Gov'
      environmentShortName: prod
      environmentCloud: azureusgovernment
      resourceGroupName: usaf-naas-prod
      alias: nichao
      location: usgovtexas
    secrets:
      AZURE_CREDS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMIN_PUB_KEY: ${{ secrets.ADMIN_PUB_KEY }}
      SOURCE_IP_ADDRESS: ${{ secrets.SOURCE_IP_ADDRESS }}
