name: AVH_Deploy_Manual

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy.'
        required: true
        default: Azure
        type: choice
        options:
        - Azure
        - Azure US Gov
        - Azure US Gov Dev
      environmentCloud:
        description: 'The Azure Cloud environment to deploy.'
        required: true
        default: azurecloud
        type: choice
        options:
        - azurecloud
        - azureusgovernment
      environmentShortName:
        description: 'The environment Shorten name. i.e. dev, prod, sbx'
        required: true
        type: choice
        options:
        - dev
        - sbx
        - staging
        - preprod
        - prod
      location:
        description: 'The location to deploy'
        required: true
        type: choice
        options:
        - southcentralus
        - eastus2
        - westus
        - usgovarizona
        - usgovtexas
        - usgoviowa
        - usgovvirginia
      resourceGroupName:
        description: 'The name of the Resource Group to deploy the AVH.'
        required: true
      alias:
        description: 'The alias of the user initiating this deployment.'
        required: true
        type: string
      sshSourceIp:
        description: 'Comma-separated list of IP addresses allowed for SSH.'
        required: false
        type: string
      deployBastion:
        description: 'Deploy bastion host?'
        required: false
        type: boolean

jobs:
  avh_deploy:
    name: 'Deploy Azure Virtualization Host'
    uses: Nchaos/NaaS/.github/workflows/avh_deploy.yml@master
    with:
      environment: ${{ github.event.inputs.environment }}
      environmentCloud: ${{ github.event.inputs.environmentCloud }}
      environmentShortName: ${{ github.event.inputs.environmentShortName }}
      resourceGroupName: ${{ github.event.inputs.resourceGroupName }}
      alias: ${{ github.event.inputs.alias }}
      sshSourceIp: ${{ github.event.inputs.sshSourceIp }}
      deployBastion: ${{ github.event.inputs.deployBastion }}
    secrets:
      AZURE_CREDS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMIN_PUB_KEY: ${{ secrets.ADMIN_PUB_KEY }}