name: AVH_Deploy_MAG

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'azure/**'
    - '.github/workflows/avh_deploy.*.yml'

jobs:
  avh_deploy:
    name: 'Deploy Azure Virtualization Host'
    uses: Nchaos/NaaS/.github/workflows/avh_deploy.yml@master
    with:
      environment: 'Azure US Gov Dev'
      environmentShortName: preprod
      environmentCloud: azureusgovernment
      resourceGroupName: usaf-naas-preprod
      alias: nichao
      location: usgovtexas
    secrets:
      AZURE_CREDS: ${{ secrets.AZURE_CREDENTIALS }}
      ADMIN_PUB_KEY: ${{ secrets.ADMIN_PUB_KEY }}
