name: AVH_Deploy

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The environment to deploy.'
        required: true
        default: 'development'
      resourceGroupName:
        description: 'The name of the Resource Group to deploy the AVH.'
        required: true
      location:
        description: 'Location of the Deployment.'
        required: false
        default: 'southcentralus'

  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
      location:
        required: false
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true
      ADMIN_PUBLIC_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentName }}
    env:
      ResourceGroupLocation: "southcentralus"
    steps:
      - uses: actions/checkout@v2

      # Authenticate to Azure.
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Ensure ResourceGroup is created.
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --resource-group ${{ inputs.resourceGroupName }} --location ${{ env.ResourceGroupLocation }}
            echo "Azure resource group created"
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: azure/avh.json
          parameters: azure/avh.parameters.json environment=${{ github.event.inputs.environmentName }} adminPublicKey=${{ secrets.ADMIN_PUBLIC_KEY }}
