name: AVH_Deploy

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
      environmentShortName:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environmentName }}
    env:
      location: "southcentralus"
    steps:
      - uses: actions/checkout@v2

      # Authenticate to Azure.
      - name: Azure Login
        uses: Azure/login@v1
        env:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Ensure ResourceGroup is created.
        uses: Azure/CLI@v1
        with:
          inlineScript: |
            #!/bin/bash
            az group create --resource-group ${{ inputs.resourceGroupName }} --location ${{ env.location }}
            echo "Azure resource group created"
          
      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: azure/avh.json
          parameters: azure/avh.parameters.json environment=${{ inputs.environmentShortName }} adminPublicKey=${{ secrets.ADMIN_PUB_KEY }} location=${{ env.location }}
